spring:
  datasource:
    username: root
    password:
    url: jdbc:mariadb://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTF-8 # test 대신 로컬에서 사용하는 데이터베이스명 입력할 것
    driver-class-name: org.mariadb.jdbc.Driver

  sql:
    init:
      mode: always # *.sql를 읽어들이기 위한 설정 코드

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # ddl 쿼리에 대해 콘솔에 직접 출력하는 것이 아닌 로그로 출력

    defer-datasource-initialization: true # 하이버네이트가 먼저 실행되고 이후에 *.sql이 실행되기 위한 코드

  redis:
    host: localHost
    port: 6379

logging:
  level:
    org.hibernate.SQL: debug # dml 쿼리에 대해 debug 이상의 로그 출력

flask-communication:
  image-path: /Users/mhpark/Downloads/fastcampus/data/
  file-path: /Users/mhpark/Downloads/fastcampus/result/
  under-bar: _
  image-extension: .png
  audio-extension: .wav
  video-extension: .mp4
  request-audio-api: http://localhost:8000/request_audio
  request-video-api: http://localhost:8000/request_video
